---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

ika:
  validator:
    ports:
      admin_interface_port: 1337
      network_address_port: 8080
      consensus_address_port: 8081
      p2p_port: 8084
      metrics_port: 9184
