---
# maintains file name, binary names, and anything which is not a diretcory or path

# config file names
node_config_file_name: "{{ type }}.yaml"

# keys file names
node_protocol_key_file_name: protocol.key
node_consensus_key_file_name: consensus.key
node_network_key_file_name: network.key
node_root_seed_key_file_name: root-seed.key

# Environment file names
node_environment_general_file_name: "{{ service_identifier }}.env"

# Binary file names
node_binaries:
  ika_default:
    default_binary_name: "ika-node-linux-x86"
    dest_binary_name: "{{ service_identifier }}"
  ika_cli:
    default_binary_name: "ika-cli-linux-x86.tar.gz"
    dest_binary_name: "{{ service_identifier }}-cli"
