---
---
- name: Create a tmp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ project }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy the binary file
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ project }}/bin/{{ node_service_default_binary_name[project] }}"
    dest: "{{ node_bin_dir }}/{{ project }}"
    remote_src: true
    owner: root
    group: root
    force: true
    mode: "0755"
  notify:
    - Restart service

- name: Download and unarchive the binary
  ansible.builtin.unarchive:
    src: "{{ vars[project][type].source_url }}/{{ suffix_url }}"
    dest: "{{ tmp_dir }}/{{ project }}"
    remote_src: true
    owner: root
    group: root
    mode: "0755"

- name: Copy the binary file
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ project }}/bin/{{ node_service_default_binary_name[project] }}"
    dest: "{{ node_bin_dir }}/{{ project }}"
    remote_src: true
    owner: root
    group: root
    force: true
    mode: "0755"
  notify:
    - Restart service

- name: Clean up the temporary files in /tmp
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ project }}"
    state: absent
