---
- name: Create a tmp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ project }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download and unarchive the binary
  vars:
    version_tag: "{{ ika[type].version.split('%2F')[-1].split('/')[-1] if env | default('') == 'testnet' else ika[type].version }}"
    file_ext: "{{ 'tar.gz' if env | default('') == 'testnet' else 'zip' }}"
    file_prefix: "{{ 'ika-' if env | default('') == 'testnet' else '' }}"
    suffix_url: "{{ file_prefix }}{{ version_tag }}-{{ ansible_facts['system'] | lower }}-x64.{{ file_ext }}"
  ansible.builtin.unarchive:
    src: "{{ ika[type].source_url }}/{{ ika[type].version }}/{{ suffix_url }}"
    dest: "{{ tmp_dir }}/{{ project }}"
    remote_src: true
    owner: root
    group: root
    mode: "0755"

- name: Copy the binary files
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ project }}/{{ item.src }}"
    dest: "{{ node_bin_dir }}/{{ item.dest }}"
    remote_src: true
    owner: root
    group: root
    force: true
    mode: "0755"
  loop:
    - { src: "{{ node_binaries.ika_default.default_binary_name }}", dest: "{{ node_binaries.ika_default.dest_binary_name }}" }
    - { src: "{{ node_binaries.ika_cli.default_binary_name }}", dest: "{{ node_binaries.ika_cli.dest_binary_name }}" }
  notify:
    - Restart service

- name: Clean up the temporary files in /tmp
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ project }}"
    state: absent
