---
- name: Include the ufw vars file
  ansible.builtin.include_vars:
    file: vars/ufw_rules.yml

- name: Apply UFW rules
  ansible.builtin.include_tasks: tasks/apply_ufw_rules.yml
  loop: "{{ node_ufw_rules }}"

- name: Include user creation task for ika
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ node_home_dir }}"
    directories: "{{ node_directories }}"
    log_file_path: "{{ node_log_file_path }}"

- name: Copy node configuration file
  ansible.builtin.template:
    src: "{{ env }}/{{ type }}/{{ type }}.yaml.j2"
    dest: "{{ node_config_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  notify:
    - Restart service

- name: Copy node binary
  ansible.builtin.copy:
    src: "{{ env }}/ika-node-linux-x86"
    dest: "{{ node_bin_dir }}/{{ service_identifier }}"
    owner: root
    group: root
    mode: "0755"
  notify:
    - Restart service

- name: Fetch secrets from HCP Vault and save to files
  when: fetch_validator_keys | default(false) | bool
  block:
    - name: Fetch protocol key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_protocol_key_file_name }}"
        secret_destination_path: "{{ node_protocol_key_path }}"
        secret_type: key

    - name: Fetch consensus key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_consensus_key_file_name }}"
        secret_destination_path: "{{ node_consensus_key_path }}"
        secret_type: key

    - name: Fetch network key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_network_key_file_name }}"
        secret_destination_path: "{{ node_network_key_path }}"
        secret_type: key
    
    - name: Fetch class groups key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_class_groups_key_file_name }}"
        secret_destination_path: "{{ node_class_groups_key_path }}"
        secret_type: key

- name: Copy ika general env file
  ansible.builtin.template:
    src: "{{ env }}/general.env.j2"
    dest: "{{ node_environment_general_file_path }}"
    owner: root
    group: root
    mode: "0644"

- name: Copy ika-node systemd service file
  ansible.builtin.template:
    src: "{{ env }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
